---

- name: Creates network
  hosts: undercloud
  roles:
    - { role: openstack_tasks, tags: ['os_tasks'] }
  become: True
  become_method: sudo
  become_user: root

- name: Tempest installation and configuration
  hosts: tester
  roles:
    - tester/tempest
  become: True
  become_method: sudo
  become_user: root
