---

- name: Prepare Overcloud nodes
  hosts: overcloud_nodes
  gather_facts: False
  roles:
    - post_install/overcloud_nodes_tasks
  become: true

- name: Prepare Networks, Flavors, Images and Instance
  hosts: undercloud
  gather_facts: False
  vars:
    boot_instance: true
    group_name: testpmd
  roles:
    - post_install/openstack_tasks

- name: Disable security groups for testpmd instance
  hosts: undercloud
  gather_facts: False
  vars:
    disable_security_groups: true
  roles:
    - roles/workarounds

- name: Install TestPMD on the instance
  hosts: testpmd
  gather_facts: True
  roles:
    - tester/testpmd_install
  become: true

- name: Run TestPMD
  hosts: testpmd
  gather_facts: False
  roles:
    - tester/testpmd_run
  become: true

- name: MoonGen run
  hosts: moongen
  gather_facts: False
  roles:
    - packet_gen/moongen/run
