---

- name: Creates network
  hosts: controller
  roles:
    - { role: post_install/openstack_tasks, tags: ['os_tasks'] }

- name: Tempest installation and configuration
  hosts: tester
  roles:
    - tester/tempest
