---

- name: Creates network
  hosts: undercloud
  roles:
    - { role: openstack_tasks, setup_openstack_env: True, routers_and_networks: True }
  become: True
  become_method: sudo
  become_user: root

- name: Tempest installation and configuration
  hosts: tester
  roles:
    - tester/tempest
  become: True
  become_method: sudo
  become_user: root
