- name: Create the base overcloud deploy script
  template:
    src: "templates/clouds.yml.j2"
    dest: "/etc/openstack/clouds.yml"
    mode: 0755

- name: Create network
  tags: test1
  vars:
    ansible_python_interpreter: "/root/tempest/.venv/bin/python"
  os_network:
    cloud: openstack  
    name: external_tempest
    state: present
    external: true
    provider_network_type: "{{ provider_network_type }}"
    provider_physical_network: "{{ provider_physical_network }}"
    provider_segmentation_id: "{{ provider_segmentation_id }}"

- name: Create subnet
  vars:
    ansible_python_interpreter: "/root/tempest/.venv/bin/python"
  os_subnet:
    cloud: openstack
    name: external_subnet
    allocation_pool_start: "{{ allocation_pool_start }}"
    allocation_pool_end: "{{ allocation_pool_end }}"
    cidr: "{{ cidr }}"
    dns_nameservers: "{{ dns_nameservers }}"
    enable_dhcp: True
    network_name: external_tempest
    state: present

- name: Get network-id
  vars:
    ansible_python_interpreter: "/root/tempest/.venv/bin/python"
  os_networks_facts:
    cloud: openstack
    name:  external_tempest
- debug: var=openstack_networks

- name: Run config_tempest script
  vars:
    ansible_python_interpreter: "/root/tempest/.venv/bin/python"
  shell: '{{ tempest_dir }}tempest/.venv/bin/python {{ tempest_dir }}tempest/tools/config_tempest.py --create --debug --image {{ osp_image }} identity.uri {{ osp_auth.stdout }} identity.admin_password {{ osp_password.stdout }}  --network-id {{ openstack_networks[0].id }}'
  args:
    chdir: '{{ tempest_dir }}/tempest'

