---

- name: 'Reload the systemctl daemon'
  command: systemctl daemon-reload

- name: 'Restart the openvswitch-nonetwork service'
  service:
    name: openvswitch-nonetwork.service
    state: restarted

- name: 'Restart openstack-nova-compute service'
  service:
    name: openstack-nova-compute.service
    state: restarted

- name: 'Restart and enable neutron-openvswitch-agent service'
  service:
    name: neutron-openvswitch-agent.service
    enabled: yes
    state: restarted

- name: 'Restart and enable OVDK service'
  service:
    name: openvswitch.service
    enabled: yes
    state: restarted

