---

- name: Setup Openstack environment
  tags:
    - os_tasks
    - setup_os_env
  include: setup_openstack_env.yml

- name: Create router and networks
  tags:
    - os_tasks
    - create_networks
  include: create_networks_and_routers.yml

- name: Upload images
  tags:
    - os_tasks
    - images_upload
  include: upload_images.yml
