- name: Download images
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.url | basename }}"
  with_items: "{{ images }}"

- name: Upload images
  vars:
    ansible_python_interpreter: "/root/.venv/bin/python"
  os_image:
    cloud: openstack
    name: "{{ item.name }}"
    container_format: bare
    disk_format: qcow2
    state: present
    filename: "/tmp/{{ item.url | basename }}"
    is_public: yes
  with_items: "{{ images }}"

- name: Remove images files
  file:
    path: "/tmp/{{ item.url | basename }}"
    state: absent
  with_items: "{{ images }}"
