---

- name: Restart nova compute service
  service:
    name: openstack-nova-compute.service
    state: restarted

- name: Reload the systemctl daemon
  command: systemctl daemon-reload

- name: Start virtual-function service
  service:
    name: virtual-function.service
    state: restarted
    enabled: yes
