---


##Static variables
repo1: http://download.devel.redhat.com/rel-eng/latest-RHEL-7/compose/Server/x86_64/os/
repo2: http://download.devel.redhat.com/rel-eng/latest-RHEL-7/compose/Server/x86_64/debug/tree
tunedtar: http://perf1.perf.lab.eng.bos.redhat.com/atheurer/tuned-profile-cpu-partitioning.tgz 

##Do not enter CPU0,on NFV scenarios use the Numa node of your PCI NIC 
isolated_cores: 4,6,8,10,12,14
