---

- name: Set an Undercloud host
  hosts: localhost
  gather_facts: no
  vars:
    undercloud_host: "{{ host }}"
    undercloud_user: "{{ user | default('stack') }}"
    undercloud_private_key_file: "{{ ssh_file | default(omit) }}"
  tasks:
      # Flash in-memory inventory in order to recreate
      # the inventory file with the new parameters
    - meta: refresh_inventory

    - name: Add undercloud to host list
      add_host:
        name: "{{ undercloud_host }}"
        groups: "undercloud,tester"
        ansible_ssh_host: "{{ undercloud_host }}"
        ansible_ssh_user: "{{ undercloud_user }}"
        ansible_ssh_private_key_file: "{{ undercloud_private_key_file | default(omit) }}"

    - name: Generate Inventory file
      template:
        src: '../../../roles/post_install/tripleo_inventory/templates/inventory.j2'
        dest: "{{ lookup('env', 'PWD') }}/inventory"

- name: Create TripleO inventory
  hosts: undercloud
  roles:
    - post_install/tripleo_inventory
  vars:
    overcloud_private_key: "{{ inventory_dir }}/id_rsa_overcloud"
    overcloud_user: heat-admin

- name: Update inventory and ansible.ssh.config files
  hosts: localhost
  tasks:
    - name: Update ansible.ssh.config for SSH tunneling
      template:
        src: '../../../roles/post_install/tripleo_inventory/templates/ansible.ssh.config.j2'
        dest: "{{ inventory_dir }}/ansible.ssh.config"

    - name: Generate Inventory file
      template:
        src: '../../../roles/post_install/tripleo_inventory/templates/inventory.j2'
        dest: "{{ inventory_dir }}/inventory"
