# Switch port config
tigon01:
  ports:
    - GigabitEthernet4/0/1
tigon02:
  ports:
    - GigabitEthernet4/0/2
tigon03:
  ports:
    - GigabitEthernet4/0/3
tigon04:
  ports:
    - GigabitEthernet4/0/4
tigon05:
  ports:
    - GigabitEthernet4/0/5
tigon06:
  ports:
    - GigabitEthernet4/0/6
tigon07:
  ports:
    - GigabitEthernet4/0/7
tigon08:
  ports:
    - GigabitEthernet4/0/8
tigon09:
  ports:
    - GigabitEthernet4/0/9
tigon10:
  ports:
    - GigabitEthernet4/0/10
tigon11:
  ports:
    - GigabitEthernet4/0/11
