---

- name: Restart controller service
  service:
    name: openstack-nova-scheduler.service
    state: restarted

- name: Reload the systemctl daemon
  command: systemctl daemon-reload

- name: Restart the neutron service
  service:
    name: neutron-server.service
    state: restarted
