---

rc_file: /home/stack/overcloudrc

## Tempest variables
tempest_user: stack
tempest_dir: /home/stack/tempest
tempest_main: openstack-tempest
tempest_conf: python-tempestconf
nfv_tempest_plugin: nfv-tempest-plugin
neutron_tempest_plugin: neutron-tempest-plugin

tempest_repos:
  - name: openstack-tempest
    url: https://github.com/openstack/tempest
    version: 17.2.0
  - name: python-tempestconf
    url: https://git.openstack.org/openstack/python-tempestconf
    version: 1.1.3
  - name: nfv-tempest-plugin
    url: https://github.com/redhat-openstack/nfv-tempest-plugin
    version: master
  - name: neutron-tempest-plugin
    url: https://github.com/openstack/neutron-tempest-plugin
    version: master
