---

hugepages_size: 1GB
hugepages_count: 16
cores_ovs: 2

dpdk_nic_name: enp5s0f1
bridge_vlan_name: br-vlan

## Physical network that is used for sriov
physical_network: physnet

## The following value sets the number of PMD the openvswitch will use, please provide them as list.
## In case of HT mode, please use sibling threads.
#For example:
#list_pmds: 4,20,6,22
