---

- name: Overcloud repo install
  include: ../post_install/overcloud_repo_install.yml

- name: DPDK - Compute
  hosts: compute
  roles:
    - nfv/dpdk/compute
  become: True
  become_method: sudo
  become_user: root
