---

- name: Restart nova compute service
  service:
    name: openstack-nova-compute.service
    state: restarted

- name: Reload the systemctl daemon
  command: systemctl daemon-reload

- name: Restart the neutron service
  service:
    name: neutron-server.service
    state: restarted
